name: Pi - Clima 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

   # - name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag pi-clima:$(date +%s)
      
      
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - 
        name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2.2.0
      - 
        name: Docker Buildx Bake
        uses: docker/bake-action@v3.1.0
      - 
        name: Docker Metadata action
        uses: docker/metadata-action@v4.6.0
      -
        name: Login to DockerHub
        uses: docker/login-action@v2 
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Build and push Docker images
        uses: docker/build-push-action@v4

        with:
          context: ./
          file: ./Dockerfile
          platforms: linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USER }}/pi-clima:latest
